name: Node CI

on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
      - name: Add artifact to github
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dist
  gh-pages:
    needs: [build]
    name: gh-pages
    runs-on: ubuntu-latest
    # only on master
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # default: public
